### ISSUE TITLE
italics for plant names

### ISSUE THREAD

**Issue by tmyersdn** [Ghini/ghini.desktop#154]
@mfrasca & @RoDuth 

The issue of using italics when formatting plant names is an issue wider than ABCD or other data standards. It relates more institutional preference - there is no binding rule:

See: International Code of Nomenclature for algae, fungi, and plants
http://www.iapt-taxon.org/nomen/main.php?page=pf&emph=italics

"As in all recent editions, scientific names under the jurisdiction of the Code, irrespective of rank, are consistently printed in italic type. **The Code sets no binding standard in this respect, as typography is a matter of editorial style and tradition, not of nomenclature.** Nevertheless, editors and authors, in the interest of international uniformity, may wish to consider adhering to the practice exemplified by the Code, which has been well received in general and is followed in a number of botanical and mycological journals."

If possible I would suggest a function to enable name formatting to be configured by the user. But I realize this will not be a priority!

**Comment by RoDuth** [comment]
Very interesting point @tmyersdn.  I know when we first started looking into this it was quite the controversial issue amongst the local plant groups.  Seemed there where several differing opinions and in the end we came to the standard that we now use by consensus. It is written up in a guide sheet that we all stick to and distribute to anyone who cares.  So yes, you are absolutely right formatting is not written in stone anywhere, there is no "law" that states that this is italicised and that isn't.  As I keep saying taxonomy is a fuzzy art.  

When I was studying I was always taught to write common names not in italics, in double inverted commas and with capitalised first letters.  At the MRBG the convention was similar but not to use the quotations.  Along the same lines we developed a list of "correct" common names for everything as some species had multiple common names.  We all wanted to get some kind of a local standard going so that our documentation wasn't confusing for the general public.

This is why I still advocate that it is NOT a major concern of the database itself to get it absolutely right.  Follow the most obvious conventions yes but if that means a couple of entries don't print quite right on screen then no problem in my books.  The database is about storing data in a way that we can get maximum benefit from.   The data needs to work for us, not make work for us. The report templates are where the formatting can be adjusted to whatever your needs are and that is the more important place to get it right in my opinion.  This was my point in regards to the botanist flags I guess.  

So... I guess in my opinion there is no immediate need to be able to configure the formatting within the database because there is already a method for doing this when you generate a report.  I'd almost go as far as saying that I wouldn't really care all that much if the database just showed everything in plain text... as long as I can still have control of the formatting when I use the data for reports etc. (e.g. to generate labels)

**Comment by mfrasca** [comment]
@RoDuth , I understand there is not one single way to do this right, but if we want to offer flexibility, we still better keep the parts that people use differently in separate fields.
@tmyersdn , low prio, mostly because I would not know how to structure the interface, but I think it would be nice to have this one.

**Comment by mfrasca** [comment]
thinking about it re-reading both of your interventions ... I guess the only real issue is when we're producing labels (this is also your point, @RoDuth, isn't it?), not when we're looking at running program. if that is indeed so, then I guess that @tmyersdn would be happy enough if the software enabled him to print labels with italics the way his institution prefers, which is already the case.

**Comment by tmyersdn** [comment]
thanks @mfrasca & @RoDuth

Our public display labels are always in plain text - this is to make the labels easier to read from a distance.

I was thinking that this was a more general question about the ability of the database to format names for reports, plant lists, display on screen or for generating html content for websites.

T

**Comment by mfrasca** [comment]
@tmyersdn, your list »reports, plant lists, display on screen, html content for websites« contains objects of different sorts.
- when it comes to formatting reports (of single plants, or of lists of plants), we're talking of the report plugin in ghini. you would work with someone to formally describe what you need, and the exact format in which you need it, check if there's already a mako or xsl template, or have the new template developed for you (and then please share your new template back to the community). you have seen examples of formatters, you can format stuff up to printing text in QR format. even in the case you want a specific font in postscript labels we can talk about it (as long as the copyright of the new font is compatible with the GPL).
- producing html content for websites, that you can also see as a form of formatter, and I suggest two things: option one, you use css and do the real formatting in your home style. option two, you use ghini.web.
- display on screen is a different thing and here we have the question whether you can live with the current "one size fits all", or if you want flexibility here, too. that would be difficult at the moment.

**Comment by tmyersdn** [comment]
thanks @mfrasca 
I am not able to use Ghini at present, and am out of touch with these methods and options.
I wanted to clarify that we do not use italics on our plant labels.

It would make sense to use ghini.web.

Yes, I do understand it is better for you to work directly with a user to develop formatting options!
:)
