### ISSUE TITLE
parent plant should be an hyperlink

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#178]
(suggestion from @RoDuth , in issue #176)

a Propagation may form a link from Plant to Accession.
--------------------------------------------------------------------------

the above means that a Plant may have 0 or more Propagations, and a Propagation may be the source of an Accession.
It's not clear to me whether a Propagation may be the source of multiple Accessions, and I would say not, but the software allows for it.

the Software offers information of this link, in both directions:
![screenshot from 2017-05-17 14-57-48](https://cloud.githubusercontent.com/assets/122869/26173389/3ff65d1e-3b11-11e7-9414-b5700fdfafbc.png)
![screenshot from 2017-05-17 14-58-34](https://cloud.githubusercontent.com/assets/122869/26173418/5e4bdac8-3b11-11e7-814d-4016e18b191e.png)
but these links are not clickable, what @RoDuth suggested.

Also, the link from Plant to Accession is not really there: you see the Propagations, but you can't tell if they have been used as a Source for a new Accession.

Also, why is there a Propagation section in the Accession InfoBox?

**Comment by mfrasca** [comment]
bf33ccc1cb8e0ae0eb8d21c7dfdac65515594776

**Comment by RoDuth** [comment]
just a quick thought considering:

> It's not clear to me whether a Propagation may be the source of multiple Accessions, and I would say not, but the software allows for it.

while I agree that it would be unlikely there is the possibility in situations such as a [sport](https://en.wikipedia.org/wiki/Sport_(botany)) or [forma](https://en.wikipedia.org/wiki/Form_(botany))

**Comment by mfrasca** [comment]
@RoDuth , can you clarify? I odn't see how Sport of Forma would require me that a single propagation results in several Accessions. 
In the meanwhile, I have already enforced "one accession per successful propagation". What about we wait for users to report this a blocking factor or an unreasonable limitation, I will definitely reconsider it. as of now, it makes things clearer to me.

**Comment by RoDuth** [comment]
A forma would receive a different name (i.e. only a small portion of '_Tillandsia ionantha_ var _stricta_ f. _fastigiata_'  seedlings develop the fastigiate form and it is only these that should receive the 'forma _fastigiata_' epithet, all others would be be plain '_Tillandsia ionantha_ var _stricta_').

A cutting that sports to produce a significantly different plant would likely be similar (i.e. they may receive a cultivar name or just an informal '(variegated form)' or '(red form)' extension to the name.  

The same could be true for a mutation (e.g. a variegated or dwarf form in a tray of seedlings) if there was a desire to name it differently rather than just give it a separate plant number and a note.

These would then fall outside of the normal accession rule of 'all things being the same'.  We have examples of these in the collection already although from supplied plants rather than on site propagation.  We simply separated them at the time of accessioning (i.e. when we received them).  Now that the MRBG are doing onsite propagation this is something that will be needed at some point in the future.  Being a fringe case I'm not sure your going to get a whole heap of users crying out for it but instead they'll hack a work around, which, in my opinion, is less desirable.

I think I've said it before.   Can't you just warn not enforce?  Or have a 'show used propagations' checkbox or something?  So the user is aware of what they are doing.

**Comment by mfrasca** [comment]
>  Can't you just warn not enforce

yes, and most of the times it is less work, in this case it's more work. but it is noted here (you just did). I will think about it.

**Comment by mfrasca** [comment]
interesting, so at the deepest taxonomic level, you can have a propagation trial producing plants belonging to slightly different taxa. ... not just different from their parent (that's what always happens for seed propagation when the pollen parent is different from the seed parent), but from each other. interesting. thank you.
