### ISSUE TITLE
review 'contact' table

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#200]
from @tmyersdn #138 
> contacts could include a flag for receipt of seed list and email address to use for the seed list.

**Comment by mfrasca** [comment]
@tmyersdn , it would be interesting to get a better insight in your use case.
> contacts could include a flag for receipt of seed list and email address to use for the seed list.

for the implementation, if we stay with notes, you can put this *email address to use for the seed list* in one, with category something like `<seed_list_email>`. just make very sure you don't use spaces nor dashes in the category name, or you won't be able to use the note-as-a-field.

**Comment by tmyersdn** [comment]
@mfrasca, I guess I was thinking of a situation where a garden needs to regularly contact a substantial subset of "contacts".  For us that might be to send out our seed list ("index seminum"), but it could also be for another reason (eg invitation to an event).

What you suggest sounds okay, but would a "tag" work better?  Otherwise, the user would have to repeat the category text for all relevant contacts.
