### ISSUE TITLE
window-less tagging - active tag

### ISSUE THREAD

**Issue by tmyersdn** [Ghini/ghini.desktop#28]
from overview of tags #27 

could you just call this the "active tag"?

You could use this as a buffer selection that allows you to rapidly tag a lot of items, and then you could name/save or delete the selection once you are happy with it?  I guess it could be automatically deleted at the end of each session or if the user resets the selection?

**Comment by mfrasca** [comment]
:+1: fine graining indeed, sorry myself! :laughing:

**Comment by mfrasca** [comment]
I was not thinking of rapid tagging of large selections, but it could apply to that too.

referring to large selections, you can already tag a large selection from the SearchResults window. there you use the current Ctrl-T shortcut to activate the `Tags` window and it applies to whatever selection you selected.

I was thinking of window-less tagging. and to be able to tag objects while still editing them.
so maybe I was still not doing fine grained thinking, let's see...

Ctrl-T opens the `Tags` window. we keep the functionality and we enhance it. I just opened two issues about it (#32, #33). I should open a new issue about being able to open the `Tags` window while an `Edit` window is active, so you can tag the object being edited. currently Ctrl-T does nothing if pressed while in an `Edit` window.

back to window-less tagging, I would like to have a quick active tag toggler keyboard shortcut.
like you press Ctrl-Y to activate a tag (small notification window flashes, informing you the tag was placed), and you press Ctrl-Shift-Y to deactivate the same tag (same small window flashes, informing you the tag was removed).

the choice for Y is because it is next to the T on qwerty keyboards and because it's the initial letter of the English Yes. and we would use Shift to signify: do the opposite.

in the Tags menu, you select a tag and it shows in the SearchResults and it becomes the active tag. (the active tag has a check next to it in the Tags menu).

Ctrl-Y and Ctrl-Shift-Y apply to the active tag.
and it would be active both from the SearchResults window as well as from all Editors.

**Comment by mfrasca** [comment]
todo:
- add a global active tag, marked with a check in the tags menu
- add two global shortcuts, Ctrl-Y and  Ctrl-Shift-Y, to activate window-less tagging.
- define a briefly flashing window to notify the user about the result of the action.

**Comment by mfrasca** [comment]
step 1 is done: add a global active tag, marked with a check in the tags menu
