### ISSUE TITLE
Template - labels small with QR code and name

### ISSUE THREAD

**Issue by Christophe80** [Ghini/ghini.desktop#283]
Hello, I've installed Ghini on a freshly installed Mac with OS Sierra High (I've done a clean install to get Ghini working :D). After several fails, Ghini runs great now... except for the reports.  I installed Mako, but several templates do not work.  I get a blank page if I use accession-label.svg, when I use accession-label-qr.svg everything seems to work fine, but I get only a number and a QR code... (see screenshot) the only thing I really mis is the plant name.   

Is there an easy way to just add the name? species etc? I have basic programming knowledge (I mean REALLY basic ;) ) but when I open the .SVG files to change them it was full of unreadable lines, and not easy to change, especially not for me :s 

Can anyone help me, or is there a link to download standaard templates? I just want a standard, small label with QR code, name and species, and a readable number... accession-label-qr.svg with a name field added I hoped... but I think I was mistaking? 

Can someone PLEASE HELP :D me ? I tried my friend Google, but he didn't help me much... I made an account on GitHub, but found nothing related to templates? 

I won't give up, but it can't be that hard?? :s It's not that I have absolutely no knowledge, but here I'missing something important I guess.
Many thanks in advance!!!! And: I really love Ghini!!!! (but I'm unable to fully use it for the moment)
![schermafbeelding 2017-10-01 om 21 30 41](https://user-images.githubusercontent.com/32431165/31230483-755439e4-a9e4-11e7-9863-b64276a461ae.png)
![schermafbeelding 2017-10-01 om 21 40 39](https://user-images.githubusercontent.com/32431165/31230490-7b766efa-a9e4-11e7-85d4-e0e54f2ec519.png)

**Comment by mfrasca** [comment]
I'm afraid that you're missing knowledge about [mako](http://www.makotemplates.org/).
every template is used to produce text based on the `values` variable.
`values` contains the top level selection from ghini.
the reports plugin defines `get_plants_pertinent_to`, `get_locations_pertinent_to`, `get_species_pertinent_to`, `get_accessions_pertinent_to` so you can produce a report of all plants in a location by simply selecting the location in ghini and invoking the report.

there's a complication in adding species information in the report, because the report is written so that you can produce labels for plants not yet in the database, so no species information available.

I have been working at it after your initial report on the [bauble/ghini forum](https://groups.google.com/forum/#!topic/bauble/f3dGBOs22kM/overview), but my edits include changes in the software itself, so you'll need be patient until I release the development line on the stable line. I want to reconsider what I did, maybe it's possible to achieve the same without change the software (preferable).

**Comment by Christophe80** [comment]
I'll agree that i'm missing knowledge about Mako, I didn't know it untill i installed Ghini.  I'm just an 'end-user' with little basic programming knowledge ;) 

The example that you showed on the forum is exactly wat i was looking for, so I'm entering all my plants in the database now and have patient untill you update the template.  Many thanks in advance! 

In the meantime, I'll browse the web to learn more about all the programming stuff ;) I'll install Ghini later on a freshly installed mac and will document all the errors or difficulties that I see as 'a normal end-user' if that can help in any way?

**Comment by mfrasca** [comment]
> In the meantime, I'll browse the web to learn more about all the programming stuff ;) I'll install Ghini later on a freshly installed mac and will document all the errors or difficulties that I see as 'a normal end-user' if that can help in any way?

yes do that please! documentation contributions highly welcome!!!

by the way, if you want to see the software show in Dutch, have a look at [our translation site](https://hosted.weblate.org/projects/ghini/)

**Comment by mfrasca** [comment]
I'm working at it, please be patient, the result will be a Postscript file, not any more SVG. I have to alter the `label.ps` template on which I had been working a couple of years ago. will take ~12h work and I will not be working full time. the bulk of the work will be moving stuff around, defining start and end of page, and scaling the code once produced. the QR producing code comes from the pyqrcode module, which we already have in ghini.

```python
def no_sirve(self, text):
    import StringIO
    import pyqrcode
    epsbuffer = StringIO.StringIO()
    qr = pyqrcode.create(text)
    qr.eps(epsbuffer)
    return '\n'.join([i for i in epsbuffer.getvalue().split('\n')
                      if not i.startswith('%')])
```

**Comment by mfrasca** [comment]
update to 1.0.74, enjoy (`accession-label-qr.ps`) or suggest corrections in a new issue.
