### ISSUE TITLE
consider EOL as taxonomic source

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#440]
@tmyersdn hinted at this resource: 
http://eol.org/api/
I'm not yet sure what to think about it, reason enough to make a note of it and have a look some day.

for example:
http://eol.org/api/search/1.0.json?q=Olea%20europea&page=1&exact=true

the result is not really as uniform as one would wish. sometimes you go to `results[0][title]` and have the complete binomial with authorship, or `results[1][title]`, or `results[0][content]` and then split by `;` and choose the best match.

**Comment by tmyersdn** [comment]
hah, and check this out for wikispecies: **https://github.com/ropensci/taxize/issues/113**

**Comment by mfrasca** [comment]
> hah, and check this out for wikispecies: **[ropensci/taxize#113](https://github.com/ropensci/taxize/issues/113)**

nope, less interesting, less complete.  
compare for Olea europea: [wikispecies](https://species.wikimedia.org/w/api.php?action=opensearch&search=olea%20europea) and [EOL](http://eol.org/api/search/1.0.json?q=Olea%20europea&page=1&exact=true)

**Comment by mfrasca** [comment]
this is becoming actual again, because TPL is offline and I don't quite manage to get an idea of when this is going to be fixed.  having two independent options would help.
with EOL I don't see how they represent the synonymy information.

**Comment by tmyersdn** [comment]
EOL appears to offer synonyms here:
**http://eol.org/api/docs/pages**

as does GBIF here:
**https://www.gbif.org/developer/species**
predictably, they have a maps api as well

out of curiosity, have you looked up species using the National Center for Biotechnology Information?This gives good insight into molecular work going on:
**https://www.ncbi.nlm.nih.gov/home/develop/api/**
(but no help at all for your question about synonyms)

**Comment by mfrasca** [comment]
hi @tmyersdn, and thank you for checking and investigating, but please don't add too many things here, or I get lost.  let's just focus on EOL, please!
I had a next look at it:
- online documentation isn't exactly high standards: calling the api from their web site gives consistently `Sorry, there was an error: error` (not particularly informative):
![image](https://user-images.githubusercontent.com/122869/47683539-e00b8580-db9d-11e8-8c80-a76b56762024.png)
- I look up 'Sterculiaceae' and I find Malvaceae and nothing about Sterculioideae.
- I am still a bit confused about synonymy information.  I tried with Iris florentina L. (a synonym of Iris germanica L.) and I get three results, twice the same name 'iris germanica', once the name 'iris germanica var. florentina'.  synonyms are `;` separated values in the `content` field.

looks like, given any search, they only provide accepted names, you then have to look up your searched object inside the `content` fields.  all the results will contain your search.

for each name, `content` fields contains it up to three times: plain, with authorship, with authorship and year of publication.

for some searches, if you give `exact=true`, you get no results (http://eol.org/api/search/1.0.json?q=Abies%20argentea&page=1&exact=true), for other searches, if you omit `exact=true` you get far too many results (http://eol.org/api/search/1.0.json?q=Iris%20florentina).

**Comment by tmyersdn** [comment]
Hi @mfrasca

Apologies, when I recommended EOL, it is simply as one of several possible services to make use of.  I currently prefer GBIF as I find it is gives better information about synonyms, also it is more international in its governance, head office in Copenhagen.
**https://www.gbif.org/species/search?q=sterculiaceae**
**https://en.wikipedia.org/wiki/Global_Biodiversity_Information_Facility**

**EOL problems** - looking at the EOL main webpage, they say "A new version of EOL is getting ready for launch—thank you for your patience!" - so this may be why the API is not responding. Actually, even searches on the webpage seem to fail at present.  Possibly EOL will be better and easier to use in the upgrade.

**too many results** - this could be due to the web service drawing on many sources - reporting all the versions of the name that have been fed into the service, for example those with different authors, those with abbreviated or standard authors, those with subspecies.

I have also been using The Name Resolution Service, which is designed for users to submit whole lists of names (which is why I have not recommended it).  Look up _Rubus fruticosus_, and you will see 20 results with one selected accepted name.  This service draws data from The Plant List amongst others, and also has an api, but because it works with lists I have not recommended it for the current problem.  However, it is interesting to see how they select the accepted name.
**http://tnrs.iplantcollaborative.org/TNRSapp.html**

**Comment by mfrasca** [comment]
Hi Tom, no need to apologize, absolutely!  I only say I prefer each issue to focus on one aspect.  so I'm closing this EOL one (I think it's too much work, interpreting their irregular data) and will copy your last GBIF suggestion to a new issue.  I just opened a couple of pages and I like the way their data is organized.  they also do not seem to do subfamilies, too bad.

**Comment by mfrasca** [comment]
![image](https://user-images.githubusercontent.com/122869/47826993-41bc2300-dd49-11e8-916b-bc80c9ffa03d.png)
Tom, I have a doubt here …
Sterculiaceae, and all other families brought under Malvaceae, that's not a synonym for Malvaceae, is it?  I understand it is a synonym of Sterculioideae, which is a subfamily of Malvaceae.
TPL does not attempt answering the question, while GBIF provides the above answer.

maybe you have examples at lower rank, like an established genus, later considered synonym of a new subgenus...  ?

**Comment by tmyersdn** [comment]
Hi @mfrasca, my (rather poor) understanding is that synonym status is based on scientific literature and the opinion of authors.  It looks like Sterculiaceae was placed in Malvaceae as part of APG (3)

**http://www.mobot.org/MOBOT/research/APweb/**
"... A.P.G. (2003) broadened the circumscription of Malvaceae because of the para/polyphyly of some of the families that had historically been associated with it (Judd & Manchester 1997; Alverson et al. 1999; Bayer et al. 1999). These families, particularly Tiliaceae and Sterculiaceae, were not at all easy to distinguish, their close relationship had long been recognized (see e.g. Brown 1814), and to some workers, at least, their combination was something of a relief. Although most of the larger clades within Malvaceae s.l. remain difficult to distinguish, even with flowers, Cheek (2007) opted for their wholesale and novel dismemberment into ten families; the "very good reasons" for doing this are wanting."

But also, have a look at this under "Botany" **https://en.wikipedia.org/wiki/Synonym_(taxonomy)**
"In botanical nomenclature, a synonym is a name that is not correct for the circumscription, position, and rank of the taxon as considered in the particular botanical publication. It is always "a synonym of the correct scientific name", but which name is correct depends on the taxonomic opinion of the author."

And check out "heterotypic synonyms" - does this sound like what has happened to Sterculiaceae?

T

**Comment by mfrasca** [comment]
Hi Tom, "heterotypic synonyms", that's two names for the same thing at a comparatively high rank, where the type species is not the same.  I don't know whether this is what happened to Sterculiaceae/Sterculioideae, but I suppose not.  
you know I'm not a taxonomist, not even a botanist, so I base my knowledge on rather sparse reading, glueing things together as if it was possible to glue things together in botany, not as much of a science as mathematics in my opinion.  as you say, much of this we are discussing is based on opinions, and representing opinions in databases is **complicated**, in particular it is complicated to represent **conflicting** opinions.  Ghini's database does not even attempt that.  the database structure allows for one set of opinions, not alternative opinions on the same objects.  
the statement that best represents my understanding is what you read in the first sentence of [the wikipedia page for Sterculia](https://en.wikipedia.org/wiki/Sterculia).
cheers and thanks, M
