### ISSUE TITLE
Column 'note' cannot be null

### ISSUE THREAD

**Issue by mfrasca** [Ghini/ghini.desktop#88]
@delphic80 is this issue coming from your computer?
is it just a note to myself, or does it get reported to you as a user as well?

(_mysql_exceptions.OperationalError)
(1048, "Column 'note' cannot be null")
[SQL: u'INSERT INTO plant_note (date, user, category, note, plant_id, _created, _last_updated) VALUES (%s, %s, %s, %s, %s, now(), now())']
[parameters: (datetime.date(2016, 4, 10), 'Adam', None, None, 35L)]

**Comment by delphic80** [comment]
I am indeed receiving this error. It happens when I try to insert a image. In previous versions the image insert worked well. If I insert a note with all required fields entered it will work. I have now had to setup an independent image repository which makes things quite fragmented.

**Comment by delphic80** [comment]
The other thing to be raised along with this bug is how it was detected. It appears that Bauble / Ghini is "phoning home" without permission. I did not register my email address in the Institution dialog box yet errors generated on my computer (and really, someone who was skeptical might also ask and what else) are being transmitted over the Internet without my permission or knowledge. While this might be a "feature" useful in tracking and identifying bugs I would strongly urge you to remove this as a matter of priority. Once customers loose faith in a software product's ability to honor and respect their privacy and their important and even proprietary data they will leave in flocks.

**Comment by mfrasca** [comment]
> It appears that Bauble / Ghini is "phoning home" without permission

you have (inadvertently?) switched on the configuration variable `use_sentry_client`. this variable is per default set to `False` and it is quite difficult to locate it. it is largely undocumented, but it is mentioned in the (new) "welcome" letter I write to people who do register.

**Comment by mfrasca** [comment]
> It happens when I try to insert a image

curious. just yesterday I was associating an image to a plant, I tested it today again and it works fine.

I manage to get your error if when entering an image I enter a user name and do not select an image. same error when entering a generic note and again specify a user name and not write any text.

**Comment by delphic80** [comment]
Thank you for looking into this potential issue for me. I will try again and document every step I do if I receive the error again.

**Comment by mfrasca** [comment]
to summarize:
- according to the database, field 'note' cannot be empty,
- the user is allowed to click on 'ok' even with an empty 'note',
- the database complains and won't allow it.
- the problem is found late and a user might not associate the technical diagnosis to the source of the problem.
